
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: bioforge_dev
      POSTGRES_USER: bioforge_user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: