services:
  - type: web
    name: bioforge
    env: python
    region: oregon
    buildCommand: "apt-get update && apt-get install -y libmagic1 && pip install -r requirements.txt"
    startCommand: "flask db upgrade && gunicorn 'app:create_app()'"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bioforge-db
          property: connectionString
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: DEFAULT_USER_PASSWORD
        value: "temporal123"

databases:
  - name: bioforge-db
    databaseName: bioforgepro_db
    user: bioforgepro_db_user