"""Add preferences column to users

Revision ID: 142e2fd07f9e
Revises: b502a6c406f7
Create Date: 2025-11-09 11:31:55.053056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142e2fd07f9e'
down_revision = 'b502a6c406f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###
