"""Añadir telegram_id a Assistant

Revision ID: 471259db0e38
Revises: d6fb18432e7d
Create Date: 2025-09-15 18:42:32.483910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471259db0e38'
down_revision = 'd6fb18432e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_assistants_telegram_id'), ['telegram_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistants_telegram_id'))
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###
