"""Agregar campo slug a Publication

Revision ID: 74299d044471
Revises: 86b41dba543d
Create Date: 2025-09-23 15:53:02.669349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74299d044471'
down_revision = '86b41dba543d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_publications_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
