"""Agregar sistema de anuncios corregido

Revision ID: 78d31103e5d2
Revises: 142e2fd07f9e
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d31103e5d2'
down_revision = '142e2fd07f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Agregar columnas como NULLABLE primero
    op.add_column('users', sa.Column('logo_profesional', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('banner_anuncio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('es_destacado', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('prioridad_anuncio', sa.Integer(), nullable=True))
    
    # Poblar las columnas con valores por defecto para filas existentes
    op.execute("UPDATE users SET es_destacado = FALSE")
    op.execute("UPDATE users SET prioridad_anuncio = 0")
    
    # Cambiar a NOT NULL con valores por defecto
    op.alter_column('users', 'es_destacado', nullable=False, server_default=sa.text('false'))
    op.alter_column('users', 'prioridad_anuncio', nullable=False, server_default=sa.text('0'))
    
    # Crear tabla anuncios
    op.create_table('anuncios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('url_destino', sa.String(length=500), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.Column('posicion', sa.String(length=50), nullable=True),
    sa.Column('orden_visualizacion', sa.Integer(), nullable=True),
    sa.Column('contador_clics', sa.Integer(), nullable=True),
    sa.Column('contador_impresiones', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profesional_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anuncios')
    op.drop_column('users', 'prioridad_anuncio')
    op.drop_column('users', 'es_destacado')
    op.drop_column('users', 'banner_anuncio')
    op.drop_column('users', 'logo_profesional')
    # ### end Alembic commands ###