"""renombrar columna role a role_name

Revision ID: b385e5aea0ba
Revises: d1f80a419bee
Create Date: 2025-09-20 00:16:44.978795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b385e5aea0ba'
down_revision = 'd1f80a419bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###
