"""Add email_verified field to User

Revision ID: b502a6c406f7
Revises: 9ca7703b4013
Create Date: 2025-10-21 14:52:36.837095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b502a6c406f7'
down_revision = '9ca7703b4013'
branch_labels = None
depends_on = None


def upgrade():
    # Aplicar la restricción NOT NULL
    op.alter_column('users', 'email_verified', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
