"""Hacer clinic_id nullable en Assistant y Task

Revision ID: d6fb18432e7d
Revises: 
Create Date: 2025-09-15 12:34:57.271776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fb18432e7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_assistants_doctor_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistants_doctor_id'), ['doctor_id'], unique=False)
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
