"""Añadir whatsapp a company_invites

Revision ID: df3c70bc952a
Revises: b385e5aea0ba
Create Date: 2025-09-20 16:28:12.942768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3c70bc952a'
down_revision = 'b385e5aea0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_invites', schema=None) as batch_op:
        batch_op.drop_column('whatsapp')

    # ### end Alembic commands ###
